server:
  port: 10007
#########################################################  
spring:
  application:
    name: gate-server
#########################################################  
eureka:
  client:
    service-url:
      defaultZone: http://10.6.221.129:10003/eureka
  instance:
    instance-id : ${spring.application.name}:${spring.profiles.active}:${server.port} 
    lease-renewal-interval-in-seconds: 5
    status-page-url-path: ${server.servlet.context-path}/actuator/info
    health-check-url-path: ${server.servlet.context-path}/actuator/health    
#########################################################      
zuul:
  routes:
    app-one-services:
      path: /app-one-api/**
      serviceId : app-one-services
      strip-prefix: false
    app-two-services:
      path: /app-two-api/**
      serviceId : app-two-services
      strip-prefix: false